### ISSUE TITLE
ToDo Develop Use Case Review Method

### ISSUE THREAD

**Issue by debpaul** [tdwg/cd#30]
Hello @tdwg/cd 

**GOAL:** to create an agreed format, before analyzing use-cases, in order to support CD data model development and testing. Once we agree on the format, we will begin breaking down the use cases. Thanks for your review.

- [ ] Please review this [use-case breakdown method](https://docs.google.com/spreadsheets/d/1SsfwogZ88TgouDJ7EoDqXJFol-eVs7aYdFx504qJNzc/edit?usp=sharing) (as soon as possible - say by April 25th - 1 week from now)
- [ ] Note any criteria missing that you will need for developing/testing the data model.
- [ ] Please add missing criteria, or comments on the method, as comments to this issue. Thanks.

This method was used by Olaf Banki at a recent ICEDIG Meeting to develop a vision for a collections digitization dashboard (CDD) model for SYNTHESYS+ to use to build a CDD for DiSSCo.

Note, for example, we decided we should add a dimensions column
- [ ] dimensions column added (where we say what dimensions this use case requires). See what we mean by dimensions in the [V 1.0 CD data model](https://docs.google.com/document/d/1KPOJM0WnZGyXCP--k-IKHiPpXIBZNHV6Ifob9DuuG3g/edit?usp=sharing)
- [ ] for each use case, we will look at the data elements to figure out what dimensions must be in place to support these data types. We will note any elements that don't fit into any of the current dimensions.
- [ ] **metrics** may be a missing dimension that we need to add to the model

For your reference, here is a much more complicated [use case breakdown model from RDA](https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.google.com_document_d_1RpJaNzB9x1W5-5F-5FBRkeTojoAD3YaZrhvpfYhsbmZ2qZ8_edit&d=DwMGaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=DPqlJuTsg-CVRxh2WLQstnhdxVemZaLl0XBmzet5JLI&s=tmyVG6McDahEuK8gNDpuoxlkuYdJc1eLDvHCFViEj1k&e=). It incorporates many more levels of information (e.g. "concepts of operations" - or imagining the requirements dictated by the data, say, for how to move the data around, or keep it up-to-date, or how to share it).

Scope: note too that scope for CD is at the collections-level (not individual specimens). So only use cases in the ICEDIG example relevant to collections are pertinent to consider for this effort.

**Comment by DaveASmith** [comment]
Hi All,
Just been looking at the ICEDIG Use Cases, and feel that a group of stakeholders is missing.

This maybe inherent within the ‘Collections Managers’, since in small institutes and many US institutions it is they who manage exhibits.

I feel that Exhibition Content Developers are a potential stakeholder of CD’s.  In pulling together content (items and knowledge), reference to repositories of a particular type of material would be very beneficial. 
Data elements required would include:
-	Taxonomic
-	Common name
-	Type of objects
-	Preservation
-	Geography
-	Stratigraphy
-	Collector
-	Expedition name

**Comment by connierinaldo** [comment]
I also think that (Museum/Herbarium) Librarians and Archivists are missing from the use case list, particularly those whose library collections have been built along with the specimen collections.  I would suggest similar data elements as for collection managers and content developers.  

Taxonomic names
Common name
Types of objects
Preservation
Copyright/Use status
Geography
Collector
Collection Name
Expedition name
Collection Dates
